<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class CertificateKeyRequest extends FormRequest
{
    protected function prepareForValidation()
    {
        if (auth()->check()) {
            $this->merge([
                'generated_by' => auth()->user()->id,
            ]);
        }
        if ($this->has('authorized')) {
            $this->merge([
                'authorized_hash' => occu_hash($this->input('authorized')),
            ]);
        }
    }

    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'certificate_sign' => ['required', 'string', 'exists:certificates,sign'],
            'timezone' => ['required', 'string'],
            'generated_by' => ['required', 'exists:users,id'],
            'authorized' => ['required', 'email'],
            'authorized_hash' => ['required', 'exists:users,email_hash'],
            'expires_at' => ['required', 'numeric', 'min:900'],
            'notes' => ['required', 'string']
        ];
    }

    public function messages()
    {
        return [
            'certificate_sign.required' => 'The certificate sign is required.',
            'certificate_sign.string' => 'The certificate sign must be a string.',
            'certificate_sign.exists' => 'The certificate sign does not exist.',
            'timezone.required' => 'The timezone field is required.',
            'timezone.string' => 'The timezone field must be a string.',
            'generated_by.required' => 'The generated by field is required.',
            'generated_by.exists' => 'The generated by user does not exist.',
            'authorized.required' => 'The authorized field is required.',
            'authorized.exists' => 'The authorized user does not exist.',
            'expired_at.required' => 'The expired at field is required.',
            'expired_at.numeric' => 'The expired at field must be a number.',
            'expired_at.min' => 'The expired at field must be at least 900 seconds (15 minutes).',
            'notes.required' => 'The notes field is required.',
            'notes.string' => 'The notes field must be a string.',
        ];
    }
}
