<?php

return [
    'lookout' => [
        'fishing_crew' => [
            'bp_captain',
            'bp_high_seas_master',
            'bp_coastal_master',
            'bp_first_bridge_sailor',
        ],
        'sea_crew' => [
            'high_seas_captain',
            'first_deck_officer',
            'second_deck_officer',
            'third_deck_officer',
            'high_seas_master',
            'coastal_master',
            'boatswain',
            'first_bridge_sailor',
            'deck_sailor',
            'electrotechnical_sailor',
        ],
    ],
    'engines' => [
        'fishing_crew' => [
            'bp_chief_engineer',
            'bp_first_engineer_officer',
            'bp_first_engine_room_sailor',
            'bp_engine_room_sailor',
        ],
        'sea_crew' => [
            'chief_engineer',
            'first_engineer_officer',
            'second_engineer_officer',
            'third_engineer_officer',
            'first_engine_room_sailor',
            'engine_room_sailor',
        ],
    ],
    'electrotechnicians' => [
        'fishing_crew' => [
            'helicopter_mechanic',
            'helicopter_pilot',
            'fishing_observer',
            'fishing_captain',
        ],
        'sea_crew' => [
            'hotel_equipment_technician',
            'it_specialist',
            'electrotechnical_officer',
            'electrotechnical_sailor',
            'cruise_director',
            'hotel_manager',
            'assistant_hotel_manager',
            'administrator',
            'tour_guide',
            'nature_guide',
            'plumber',
            'housekeeper',
            'boutique_manager',
            'butler',
            'launderer',
            'storekeeper',
            'carpenter',
            'language_teacher',
            'masseur',
            'photographer',
            'musician',
            'doctor',
            'nurse',
            'welder',
            'turner',
            'pump_operator',
            'electrician',
            'refrigeration_technician',
            'crane_operator',
            'shipowner_representative',
            'boatswain',
            'other_authority_roles',
        ],
    ],
    'underwater' => [
        'sea_crew' => [
            'scientific_recreational_divers',
            'commercial_divers',
        ],
    ],
];
